// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx8FghGFok4epaVggLjlMhBPeG0MLjHb4',
    appId: '1:554759914642:web:6007cf43783c935bd0924b',
    messagingSenderId: '554759914642',
    projectId: 'munro-d5bcd',
    authDomain: 'munro-d5bcd.firebaseapp.com',
    storageBucket: 'munro-d5bcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSHNOodV_JnmRfHHGof6RlrK2EzZRsqA',
    appId: '1:554759914642:android:afb3a9cac19b6252d0924b',
    messagingSenderId: '554759914642',
    projectId: 'munro-d5bcd',
    storageBucket: 'munro-d5bcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8OSaXp-kODdyIqB13OkTk1gVp8YZebTA',
    appId: '1:554759914642:ios:3b5b81180e4cbeaad0924b',
    messagingSenderId: '554759914642',
    projectId: 'munro-d5bcd',
    storageBucket: 'munro-d5bcd.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterTute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8OSaXp-kODdyIqB13OkTk1gVp8YZebTA',
    appId: '1:554759914642:ios:3b5b81180e4cbeaad0924b',
    messagingSenderId: '554759914642',
    projectId: 'munro-d5bcd',
    storageBucket: 'munro-d5bcd.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterTute',
  );
}
